Trying to fix the CI cache issue with a new commit.

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -12,6 +12,7 @@ jobs:
     name: Install, Build, and e2e Testing (iOS)
     runs-on: macos-14
     steps:
+      - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
           node-version: 18.x
@@ -55,6 +56,7 @@ jobs:
     name: Install, Build, and e2e Testing (Android)
     runs-on: ubuntu-latest
     steps:
+      - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
           node-version: 18.x
@@ -77,6 +79,7 @@ jobs:
       - name: Create AVD, start emulator, and wait for emulator to be available
         run: |
           echo "Installing dependencies"
+          sudo apt-get --quiet update --yes
           sudo apt-get --quiet install --yes \
             libc6 \
             libdbus-1-3 \
@@ -97,34 +100,46 @@ jobs:
             libgl1 \
             pulseaudio \
             socat
+            > /dev/null
 
           echo "Starting adb server"
           adb start-server
 
-          echo "Installing AOSP AVD system image"
+          echo "Installing AVD system image"
           sdkmanager --install "system-images;android-31;google_apis;x86_64"
 
-          echo "Creating AVD"
-          avdmanager --verbose create avd --force --name "pixel_4" --device "pixel_4" --package "system-images;android-31;google_apis;x86_64"
-
-          echo "Available AVDs..."
-          echo $(${ANDROID_HOME}/emulator/emulator -list-avds)
-
           ANDROID_EMULATOR="pixel_4"
-          echo "Starting emulator ${ANDROID_EMULATOR}"
-          ${ANDROID_HOME}/emulator/emulator @${ANDROID_EMULATOR} -no-audio -no-window -use-system-libs -gpu auto &
+
+          echo "Creating AVD"
+          avdmanager --verbose create avd --force --name "${ANDROID_EMULATOR}" --device "${ANDROID_EMULATOR}" --package "system-images;android-31;google_apis;x86_64"
 
           max_retries=10
           counter=0
-          while [[ $(adb shell getprop init.svc.bootanim) != "stopped" ]]; do
+          until ${ANDROID_SDK_ROOT}/emulator/emulator -list-avds | grep "${ANDROID_EMULATOR}"; do
+            echo "AVD not available yet..."
+            sleep 5
+            echo "Listing AVDs..."
+            echo $(${ANDROID_SDK_ROOT}/emulator/emulator -list-avds)
+            [[ counter -eq $max_retries ]] && echo "Could not list ${ANDROID_EMULATOR} in list of AVDs" && exit 1
+            counter=$((counter + 1))
+          done
+
+          echo "emulator version: $(${ANDROID_SDK_ROOT}/emulator/emulator --version)"
+          echo "Starting emulator ${ANDROID_EMULATOR}"
+          ${ANDROID_SDK_ROOT}/emulator/emulator @"${ANDROID_EMULATOR}" -no-audio -no-window -no-boot-anim -use-system-libs 2>&1 > /dev/null &
+
+          max_retries=10
+          counter=0
+          until adb shell getprop sys.boot_completed; do
             sleep 10
-            adb devices
-            echo "Emulator status: $(adb shell getprop init.svc.bootanim)"
-            [[ $counter -eq $max_retries ]] && echo "Failed to start the emulator!" && exit 1
+            [[ counter -eq $max_retries ]] && echo "Failed to start the emulator!" && exit 1
             counter=$((counter + 1))
           done
         env:
-          ANDROID_HOME: ${{ env.ANDROID_HOME }}
+          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
+
+      - name: Install detox cli
+        run: npm install -g detox-cli
 
       - name: Checkout 
         uses: actions/checkout@v4
